service: mirror-collective-api
frameworkVersion: '^3.0.0'

provider:
  name: aws
  runtime: nodejs18.x
  stage: ${opt:stage, 'staging'}
  region: ${opt:region, 'us-east-1'}
  memorySize: 512
  timeout: 30
  environment:
    NODE_ENV: ${self:provider.stage}
    API_VERSION: v1
    # Cognito Configuration
    COGNITO_USER_POOL_ID: ${env:COGNITO_USER_POOL_ID}
    COGNITO_CLIENT_ID: ${env:COGNITO_CLIENT_ID}
    COGNITO_CLIENT_SECRET: ${env:COGNITO_CLIENT_SECRET}
    # SES Configuration
    SES_FROM_EMAIL: ${env:SES_FROM_EMAIL, 'mirrorcollective1@gmail.com'}
    SES_REGION: ${env:SES_REGION, 'us-east-1'}
    # CORS Configuration
    ALLOWED_ORIGINS: ${env:ALLOWED_ORIGINS, 'https://your-frontend-domain.com'}
    # OpenAI Configuration (optional)
    OPENAI_API_KEY: ${env:OPENAI_API_KEY, ''}
    # Security Configuration
    BCRYPT_ROUNDS: ${env:BCRYPT_ROUNDS, '12'}
    # Rate limiting
    RATE_LIMIT_WINDOW_MS: ${env:RATE_LIMIT_WINDOW_MS, '900000'}
    RATE_LIMIT_MAX_REQUESTS: ${env:RATE_LIMIT_MAX_REQUESTS, '100'}

  # IAM Role for Lambda functions
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - logs:CreateLogGroup
            - logs:CreateLogStream
            - logs:PutLogEvents
          Resource:
            - 'arn:aws:logs:${self:provider.region}:*:log-group:/aws/lambda/*:*:*'
        # SES permissions for sending emails
        - Effect: Allow
          Action:
            - ses:SendEmail
            - ses:SendRawEmail
          Resource:
            - 'arn:aws:ses:${self:provider.region}:*:identity/*'
        # Cognito permissions for user management
        - Effect: Allow
          Action:
            - cognito-idp:AdminCreateUser
            - cognito-idp:AdminDeleteUser
            - cognito-idp:AdminGetUser
            - cognito-idp:AdminInitiateAuth
            - cognito-idp:AdminRespondToAuthChallenge
            - cognito-idp:AdminSetUserPassword
            - cognito-idp:AdminUpdateUserAttributes
            - cognito-idp:ListUsers
            - cognito-idp:SignUp
            - cognito-idp:ConfirmSignUp
            - cognito-idp:ForgotPassword
            - cognito-idp:ConfirmForgotPassword
            - cognito-idp:ResendConfirmationCode
            - cognito-idp:InitiateAuth
          Resource:
            - 'arn:aws:cognito-idp:${self:provider.region}:*:userpool/*'
        # Add additional permissions as needed for your API
        # - Effect: Allow
        #   Action:
        #     - dynamodb:Query
        #     - dynamodb:Scan
        #     - dynamodb:GetItem
        #     - dynamodb:PutItem
        #     - dynamodb:UpdateItem
        #     - dynamodb:DeleteItem
        #   Resource: "arn:aws:dynamodb:${self:provider.region}:*:table/*"

  # API Gateway configuration
  apiGateway:
    shouldStartNameWithService: true
    binaryMediaTypes:
      - 'multipart/form-data'
      - 'application/octet-stream'

functions:
  # Main API handler (health check, root)
  api:
    handler: dist/lambda.handler
    memorySize: 256
    timeout: 15
    events:
      - http:
          path: /
          method: ANY
          cors:
            origin: ${env:ALLOWED_ORIGINS, 'https://your-frontend-domain.com'}
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
            allowCredentials: true
      - http:
          path: /{proxy+}
          method: ANY
          cors:
            origin: ${env:ALLOWED_ORIGINS, 'https://your-frontend-domain.com'}
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
            allowCredentials: true

  auth:
    handler: dist/auth-lambda.handler
    memorySize: 256 # Lower memory for auth operations
    timeout: 15 # Shorter timeout for auth
    events:
      # Public auth endpoints (no authorization required)
      - http:
          path: /api/auth/register
          method: POST
          cors:
            origin: ${env:ALLOWED_ORIGINS, 'https://your-frontend-domain.com'}
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
            allowCredentials: true
      - http:
          path: /api/auth/login
          method: POST
          cors:
            origin: ${env:ALLOWED_ORIGINS, 'https://your-frontend-domain.com'}
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
            allowCredentials: true
      - http:
          path: /api/auth/forgot-password
          method: POST
          cors:
            origin: ${env:ALLOWED_ORIGINS, 'https://your-frontend-domain.com'}
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
            allowCredentials: true
      - http:
          path: /api/auth/reset-password
          method: POST
          cors:
            origin: ${env:ALLOWED_ORIGINS, 'https://your-frontend-domain.com'}
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
            allowCredentials: true
      - http:
          path: /api/auth/refresh
          method: POST
          cors:
            origin: ${env:ALLOWED_ORIGINS, 'https://your-frontend-domain.com'}
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
            allowCredentials: true
      - http:
          path: /api/auth/confirm-email
          method: POST
          cors:
            origin: ${env:ALLOWED_ORIGINS, 'https://your-frontend-domain.com'}
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
            allowCredentials: true
      - http:
          path: /api/auth/resend-verification-code
          method: POST
          cors:
            origin: ${env:ALLOWED_ORIGINS, 'https://your-frontend-domain.com'}
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
            allowCredentials: true
      # Protected auth endpoints (require Cognito authorization)
      - http:
          path: /api/auth/me
          method: GET
          authorizer:
            name: cognitoAuthorizer
            type: COGNITO_USER_POOLS
            arn: arn:aws:cognito-idp:${self:provider.region}:542298339159:userpool/${env:COGNITO_USER_POOL_ID}
          cors:
            origin: ${env:ALLOWED_ORIGINS, 'https://your-frontend-domain.com'}
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
            allowCredentials: true
      - http:
          path: /api/auth/logout
          method: POST
          authorizer:
            name: cognitoAuthorizer
            type: COGNITO_USER_POOLS
            arn: arn:aws:cognito-idp:${self:provider.region}:542298339159:userpool/${env:COGNITO_USER_POOL_ID}
          cors:
            origin: ${env:ALLOWED_ORIGINS, 'https://your-frontend-domain.com'}
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
            allowCredentials: true
      - http:
          path: /api/auth/account
          method: DELETE
          authorizer:
            name: cognitoAuthorizer
            type: COGNITO_USER_POOLS
            arn: arn:aws:cognito-idp:${self:provider.region}:542298339159:userpool/${env:COGNITO_USER_POOL_ID}
          cors:
            origin: ${env:ALLOWED_ORIGINS, 'https://your-frontend-domain.com'}
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
            allowCredentials: true

  chat:
    handler: dist/chat-lambda.handler
    memorySize: 1024 # Higher memory for AI processing
    timeout: 60 # Longer timeout for AI responses
    events:
      # All chat endpoints require Cognito authorization
      - http:
          path: /api/chat/mirror
          method: POST
          authorizer:
            name: cognitoAuthorizer
            type: COGNITO_USER_POOLS
            arn: arn:aws:cognito-idp:${self:provider.region}:542298339159:userpool/${env:COGNITO_USER_POOL_ID}
          cors:
            origin: ${env:ALLOWED_ORIGINS, 'https://your-frontend-domain.com'}
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
            allowCredentials: true

plugins:
  - serverless-offline

custom:
  serverless-offline:
    httpPort: 3001
    host: 0.0.0.0
    stage: local
    prefix: ''

# Package configuration
package:
  patterns:
    - '!src/**'
    - '!tests/**'
    - '!.github/**'
    - '!*.md'
    - '!*.json'
    - '!*.yml'
    - '!coverage/**'
    - '!docs/**'
    - '!*.log'
    - 'dist/**'
    - 'package.json'
    - 'node_modules/**'
  excludeDevDependencies: true

# CloudFormation resources
resources:
  Resources:
    # Custom domain configuration (optional)
    # ApiGatewayDomainName:
    #   Type: AWS::ApiGateway::DomainName
    #   Properties:
    #     DomainName: api.yourdomain.com
    #     CertificateArn: arn:aws:acm:us-east-1:ACCOUNT:certificate/CERT-ID

    # CloudWatch Log Group
    ApiLogGroup:
      Type: AWS::Logs::LogGroup
      Properties:
        LogGroupName: /aws/lambda/${self:service}-${self:provider.stage}-api
        RetentionInDays: 14

  Outputs:
    ApiGatewayRestApiId:
      Value:
        Ref: ApiGatewayRestApi
      Export:
        Name: ${self:service}-${self:provider.stage}-restApiId

    ApiGatewayRestApiRootResourceId:
      Value:
        Fn::GetAtt:
          - ApiGatewayRestApi
          - RootResourceId
      Export:
        Name: ${self:service}-${self:provider.stage}-rootResourceId
